<?php
// @codingStandardsIgnoreFile
/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
use Magento\Framework\App\Action\Action;
$blockName = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct');
?> <?php $productCollection = $block->getProductCollection(); ?> <?php
$postDataHelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
$jsonHelper = $this->helper(\Magento\Framework\Json\Helper\Data::class);

   if ($exist = $block->getProductCollection()) {
	   $type = 'new';
	   $mode = 'list';
	   $type = $type . ' ' . $mode;
	   $class = 'widget' . ' ' . $type;
	   $items = $exist;
	   $showAddTo = true;
	   $showCart = true;
	   $canItemsAddToCart = false;
   }
?>
<?php if ($exist):?> <div class="block 
<?= $blockName->escapeHtmlAttr($class) ?>">
<div class="block-content content" aria-labelledby="block-
<?= $blockName->escapeHtmlAttr($class) ?>-heading">
<div class="products wrapper grid products-grid products-
<?= $blockName->escapeHtmlAttr($type) ?>">
<ol class="products list items product-items" style="display:flex"> <?php foreach ($block->getProductCollection() as $_item):?> <li class="item product product-item" style="margin-left: calc((100% - 4 * 20.439%) / 3) !important;">
<div class="product-item-info "> <?php $imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
		 $productImage = $imageBlock->getImage($_item, 'category_page_grid');  /* $product pass product object here */ ?> <a href="
				<?php echo $_item->getProductUrl(); ?>"> <?php echo $productImage->toHtml()  ?> </a>
<div class="product details product-item-details">
  <strong class="product name product-item-name">
	<a class="product-item-link" title="
						<?= $blockName->escapeHtmlAttr($_item->getName()) ?>" href="
						<?= $blockName->escapeUrl($blockName->getProductUrl($_item)) ?>"> <?= $blockName->escapeHtml($_item->getName()) ?> </a>
  </strong> <?= /* @noEscape */ $blockName->getProductPrice($_item) ?> <?php if ($_item->getTypeId() ==
			\Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {
			
			$swatchBlock = $this
			->getLayout()
			->createBlock(\Magento\Swatches\Block\Product\Renderer\Listing\Configurable::class)
				->setTemplate("Magento_Swatches::product/listing/renderer.phtml");
			echo $swatchblockName->setProduct($_item)->toHtml();
			} ?> <?php if ($showAddTo || $showCart):?> <div class="product actions product-item-actions"> <?php if ($showCart):?> <div class="actions-primary"> <?php if ($_item->isSaleable()): ?> <?php
				  $postData = $postDataHelper
					 ->getPostData($blockName->getAddToCartUrl($_item), ['product' =>
					  $_item->getEntityId()]);
				  $postParams = $jsonHelper->jsonDecode($postData);
				  ?> <form data-role="tocart-form" data-product-sku="
							<?= $blockName->escapeHtml($_item->getSku()) ?>" action="
							<?= /* @NoEscape */
				   $blockName->escapeHtmlAttr($postParams['action']) ?>" method="post">
		<input type="hidden" name="product" value="
								<?= /* @escapeNotVerified */
						$blockName->escapeHtmlAttr($postParams['data']
											  ['product']) ?>">
		<input type="hidden" name="
									<?= /* @escapeNotVerified */
						$block
					   ->escapeHtmlAttr(Action::PARAM_NAME_URL_ENCODED) ?>" value="
									<?= /* @escapeNotVerified */
						$blockName->escapeHtmlAttr($postParams['data']
							[Action::PARAM_NAME_URL_ENCODED]) ?>"> <?= $blockName->getBlockHtml('formkey') ?> <button type="submit" title="
										<?= $blockName->escapeHtml(__('Add to Cart')) ?>" class="action tocart primary">
		  <span> <?= /* @escapeNotVerified */
					 $blockName->escapeHtmlAttr(('Add to Cart')) ?> </span>
		</button>
	  </form> <?php endif; ?> </div>
	<script type="text/x-magento-init"> {
				   "[data-role=tocart-form], .form.map.checkout": {
					   "catalogAddToCart": {
						   "product_sku": "
								<?= /* @NoEscape */
				  $blockName->escapeHtmlAttr($_item->getSku()) ?>"
					   }
				   }
			   }
			
</script> <?php endif; ?> <?php if ($showAddTo):?> <div class="secondary-addto-links actions-secondary" data-role="add-to-links"> <?php if ($addToBlock = $blockName->getChildBlock('addto')):?> <?= $addToblockName->setProduct($_item)->getChildHtml() ?> <?php endif; ?> </div> <?php endif; ?>
  </div> 
 <?php endif; ?>
</div>
</div>
</li> 
<?php endforeach ?> 
</ol>
</div>
</div>
</div> 
<?php endif; ?>